config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "students#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notch.rb
class Notch < ApplicationRecord
    has_many :student_proficiencies
    has_many :students, through: :student_proficiencies
  
    validates :description, presence: true
  
    enum :grade, [
      :pre_k,
      :kindergarten,
      :first,
      :second,
      :third,
      :fourth,
      :fifth,
      :sixth,
      :seventh,
      :eighth,
      :ninth,
      :tenth,
      :eleventh,
      :twelveth
    ]
end

app/models/notch_status.rb
class NotchStatus < ApplicationRecord
  belongs_to :student
  belongs_to :notch

  enum :status, [
    :not_started,
    :introduced,
    :practicing,
    :proficient
], default: :not_started
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :notch_statuses
    has_many :notches, through: :notch_statuses
    has_one_attached :profile_picture
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

    def student_params
      params.expect(student: [ :name, :profile_picture ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Growthnotch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.file_field :profile_picture, accept: "image/*" %>
  </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/students/edit.html.erb
<h1>Add Student</h1>

<%= render "form", student: @student %>
<%= link_to "Cancel", @student %>

app/views/students/index.html.erb
<h1>Students</h1>

<%= link_to "Add Student", new_student_path %>

<% @students.each do |student| %>
   <div>
      <%= link_to student.name, student %>
   </div>
  <% end %>

app/views/students/new.html.erb
<h1>Add Student</h1>

<%= render "form", student: @student %>
<%= link_to "Cancel", students_path %>

app/views/students/show.html.erb
<%= image_tag @student.profile_picture, class: "profile-small" if @student.profile_picture.attached? %>

<h1><%= @student.name %></h1>

<%= link_to "Edit", edit_student_path(@student) %>
<%= button_to "Delete", @student, method: :delete, data: { turbo_confirm: "Are you sure you want to delete this student? This cannot be undone." } %>
<%= link_to "Back", students_path %>